spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: backend

app:
  security:
    jwt:
      issuer: ${APP_SECURITY_JWT_ISSUER}
      secret: ${APP_SECURITY_JWT_SECRET}
      ttl-seconds: 3600
